### ISSUE TITLE
Has anyone modified this to connect to a Wahoo Kickr

### ISSUE THREAD

**Issue by ColinTalbert** [zacharyedwardbull/pycycling#13]
I'm starting to play around with this package, but wanted to see if anyone has successfully connected to a Kickr already.

[cscs_example.py](https://github.com/ColinTalbert/pycycling/blob/master/examples/cscs_example.py) seems like it would almost work but https://github.com/zacharyedwardbull/pycycling/blob/0806b62e14dae055673177d16615f441900f2188/pycycling/cycling_power_service.py#L16-L19  seem to be hardcoded for Tacx. 

Any help on how I could find similar values for Wahoo would be appreciated. If I get it to work I could contribute back an example for a different trainer.

Thanks,
Colin

**Comment by zacharyedwardbull** [comment]
Hi,

While I haven't been able to test it myself with a Wahoo Kickr, another user mentions having no problems using the package to retrieve data from the Kickr (see https://github.com/zacharyedwardbull/pycycling/issues/1#issuecomment-1257038724).

Cheers,
Zachary
