### ISSUE TITLE
Would you accept a pull request for Garmin Rear View Radar (Varia series) add-on?

### ISSUE THREAD

**Issue by tensorturtle** [zacharyedwardbull/pycycling#15]
Hi @zacharyedwardbull , first of all thank you for creating this package. I have used it well.
I am about to begin work on parsing the BLE packets that are sent from Garmin Varia RVR315.
I have had success so far in basic one-way retrieval, and I just need to parse the byte array to something human-readable.
Would you be interested in accepting a pull request once that work is done?

Jason

**Comment by zacharyedwardbull** [comment]
Hi Jason,

That sounds like a worthwhile addition, I'd be happy to accept a pull request 👍 

Cheers,
Zachary
