### ISSUE TITLE
cycling_power_measurement_handler not called

### ISSUE THREAD

**Issue by unicornis-pl** [zacharyedwardbull/pycycling#17]
Hi,
I noticed that rarely the handler stops being called and everything freezes. It seems that BLE packets are not coming. Happens irregularly, after 20-90 minutes of operation. I cannot figure out how to hadle it as an exception and maybe force the reconnect. Any ideas?

I am using it to contol ambient lights in my Zwift cave based on the power produced.

**Comment by zacharyedwardbull** [comment]
Hey, did you manage to resolve the problem? I'm sorry I haven't been able to help out here.
