### ISSUE TITLE
feasibility of porting this code to javascript for use within the chrome browser using the built-in bluetooth support

### ISSUE THREAD

**Issue by thethereza** [zacharyedwardbull/pycycling#19]
Not really an issue, but I was wondering if you had any idea how hard it would be port this code to Javascript running on the chrome browser, given native btle support in the browser.

**Comment by zacharyedwardbull** [comment]
I think it's definitely doable; there are already existing projects which might give a useful starting point such as https://github.com/dvmarinoff/Flux.
