### ISSUE TITLE
Works with Magene S3+ Cadence/Speed Sensor and a TUI frontend

### ISSUE THREAD

**Issue by cboddy** [zacharyedwardbull/pycycling#21]
Hello,

Firstly, thanks for releasing this library,  I've been using it with a [Magene S3+ Cadence/Speed Sensor](https://www.magene.com/product_s3.html) sensor successfully for the past few months.

Secondly in case it's of interest  - I've created [a front-end TUI for displaying the data from the sensor](https://github.com/cboddy/cycling-cadence-display) that uses `pycycling` as a driver for the sensor, you can see how it looks in this [blog-post](https://boddy.im/cycle-meter.html).

**Comment by zacharyedwardbull** [comment]
Thanks for letting me know, I added a link to your project in the README :)
