### ISSUE TITLE
PR for Python 3.8 compatibility

### ISSUE THREAD

**Issue by tensorturtle** [zacharyedwardbull/pycycling#28]
Hi @zacharyedwardbull ! I made a small PR to fix a compatibility issue in `sterzo.py` which limited it to Python >= 3.9. Please take a look!

**Comment by zacharyedwardbull** [comment]
Thanks, I've had a look and left some comments. Cheers

**Comment by tensorturtle** [comment]
Pleasure to contribute. Best wishes to you

**Comment by zacharyedwardbull** [comment]
Thanks for the help, I've just published a new release (0.3.2)
