### ISSUE TITLE
Reset Distance Travelled Value in GeneralFEData

### ISSUE THREAD

**Issue by NicksIDE7** [zacharyedwardbull/pycycling#41]
Hello, anyone not how to reste the distance travelled in GeneralFEData? 

I dont want to wait 60 minutes for automatically reset the data, while unplugging the Tacx Neo 2T.

The following code shows the distance travelled, but i cant reset it.

`
import asyncio
import pandas
import sys
from io import StringIO

from bleak import BleakClient

from pycycling.tacx_trainer_control import TacxTrainerControl

async def run(address):
    async with BleakClient(address) as client:
        def my_measurement_handler(data):
            global distance
            distance = data[2]
            print("DISTANCE TRAVELLED : {0} ".format(distance))

        await client.is_connected()
        trainer = TacxTrainerControl(client)
        trainer.set_general_fe_data_page_handler(my_measurement_handler)
        await trainer.enable_fec_notifications()
        await asyncio.sleep(100.0)
        await trainer.disable_fec_notifications()

if __name__ == "__main__":
    import os

    os.environ["PYTHONASYNCIODEBUG"] = str(1)

    device_address = "E7:AB:9F:ED:EA:2B"
    loop = asyncio.get_event_loop()
    loop.run_until_complete(run(device_address))

`

**Comment by zacharyedwardbull** [comment]
I'm not sure if there is a way to reset the distance travelled. One way you could work around this is to save whatever the distance travelled is when you want to "reset" it, and then subtract that value from future distance travelled values. You might also need some extra logic to handle wraparound (when the distance travelled goes above whatever the max in on the trainer).

Sorry this answer isn't the best, unfortunately it's a little while since I worked directly with a Tacx trainer.

**Comment by NicksIDE7** [comment]
Thank you for the comment. I guess the distance_traveled variable in GeneralFEData is an 8- Bit Value. I tested it and at 256 the value reset to zero. There should be a conversion to uint or float? Or any suggestions which type of storage area the variables have ?

**Comment by zacharyedwardbull** [comment]
See this screenshot from the ANT+ FE-C specification for the General FE data page:

<img width="698" alt="Screenshot 2024-04-30 at 22 38 45" src="https://github.com/zacharyedwardbull/pycycling/assets/34217412/ab99a312-b521-4acd-9d0b-82f91020751c">

So yep, it's an integer which gives distance in metres.

**Comment by NicksIDE7** [comment]
thank you for this answer. you are right, maybe i have to use a counter to set up a flag when the value wraparound or some other logic to fix this issue as you mentioned below.
