### ISSUE TITLE
Support for Bluetooth CYCLING POWER FEATURE Characteristic

### ISSUE THREAD

**Issue by ElreboCM** [zacharyedwardbull/pycycling#5]
It would be really cool if you could support the [Cycling Power Feature Characteristic](https://www.bluetooth.com/wp-content/uploads/Sitecore-Media-Library/Gatt/Xml/Characteristics/org.bluetooth.characteristic.cycling_power_vector.xm) as well.

**Comment by zacharyedwardbull** [comment]
Hey, many thanks for creating this issue.

I'm pretty sure we already support the cycling power feature. Try using the `get_cycling_power_feature()` method. 

Implementation at:
https://github.com/zacharyedwardbull/pycycling/blob/8cba37b28432be9d76bf5a4092f0ce453b773919/pycycling/cycling_power_service.py#L113

Let me know how you get on,
Zachary

**Comment by ElreboCM** [comment]
Hi. Yes your are right. 
I will have a closer look. I am testing it with a SRAM QUARQ AXS.

**Comment by zacharyedwardbull** [comment]
Did you manage to get pycycling to work with the SRAM QUARQ AXS in the end? Cheers

**Comment by ElreboCM** [comment]
The Power Measurement Characteristic works fine. The fact that instantaneous power is 0 is because I am spinning the crank by hand and the bike is on a stand.
 
<img width="1672" alt="image" src="https://user-images.githubusercontent.com/4703830/111864809-70abb180-8963-11eb-9bc6-b45be8bf3eef.png">


However I do not get an out put for the **Power Vector Characteristic** (I name it incorrectly for the issue) does not have an output.
Where do you print the output? I could not find it in your code...

```
import asyncio
from bleak import BleakClient

from pycycling.cycling_power_service import CyclingPowerService

async def run(address):
    async with BleakClient(address) as client:
        def my_measurement_handler(data):
            print(data)
        await client.is_connected()
        trainer = CyclingPowerService(client)
        trainer.set_cycling_power_measurement_handler(my_measurement_handler)
        #await trainer.enable_cycling_power_measurement_notifications()
        await trainer.enable_cycling_power_vector_notifications()
        await asyncio.sleep(30.0)
if __name__ == "__main__":
    import os
    os.environ["PYTHONASYNCIODEBUG"] = str(1)
    device_address = "08894FCF-5A2A-4468-78C1-A9871E2F4154"
    loop = asyncio.get_event_loop()
    loop.run_until_complete(run(device_address))
```


in your example you are twice subscribing to the Power Measurement Characteristic. I guess that is a mistake?
At least I got an error that I am already subscribed to that characteristic.

**Comment by ElreboCM** [comment]
Ah looks like I forgot to set the power vector handler properly. I Will try again when I find some time.

**Comment by ElreboCM** [comment]
<img width="1677" alt="image" src="https://user-images.githubusercontent.com/4703830/111868815-6d70ef80-897c-11eb-882c-7a9a03cf31e8.png">
That appears to be working 👍

A while ago also tested a Sigeyi AXO. That one was working too!

**Comment by zacharyedwardbull** [comment]
Glad you managed to get it to work! 

Improving the documentation is the top of my priority list for this package, hopefully I'll have a chance to do that sometime this summer.

**Comment by ElreboCM** [comment]
It is actually quite straightforward to use if you look closely at the code. Nonetheless a bit more documentation won’t harm. 

The only thing that is missing for full cycling power service support is the extreme angles field in the power management characteristic?

**Comment by ElreboCM** [comment]
One thing that strikes me however: 

If you look at the torque magnitude array you can spot values above 65000. 
This field is a signed int. Could it be that you are not taking the sign into account when doing the conversion from byte?

**Comment by ElreboCM** [comment]
Changed the code in the power vector handler to convert the intantenous force / torque to signed int

``` for i in range(byte_offset, len(data), 2):
            element = int.from_bytes(data[i:i + 2], 'little', signed="true")
```
Looking good now 😀

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/4703830/111882923-9616da80-89b8-11eb-81c3-45bc00673e48.png">

**Comment by zacharyedwardbull** [comment]
Looks like you found a bug! I'll fix this as you have done when I have a free moment. Thanks for finding it and posting a fix.
