### ISSUE TITLE
Heart rate sensor support?

### ISSUE THREAD

**Issue by sjorsgeelen** [zacharyedwardbull/pycycling#6]
I'm playing around with this repo (good stuff :smiley:!), and I was wondering whether adding heart rate sensor support would be a welcome change. 

I wouldn't mind contributing. I've got a wahoo TICKR to test against.

Cheers

**Comment by zacharyedwardbull** [comment]
Support for heart rate sensors seems like a worthwhile addition.

A PR would be really appreciated!

I found the XML files at https://github.com/sur5r/gatt-xml particularly helpful when implementing the Bluetooth profiles. For heart rate sensor you might want to look at https://github.com/sur5r/gatt-xml/blob/main/org.bluetooth.characteristic.heart_rate_measurement.xml and https://github.com/sur5r/gatt-xml/blob/main/org.bluetooth.service.heart_rate.xml.

Good luck and let me know if you have any questions.
